Upstream sync

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -8,7 +8,7 @@
 
 # ==============================================================================
 
-latest_xcode_major="13"
+latest_xcode_major="14"
 
 # ==============================================================================
 # Command functions
@@ -88,13 +88,15 @@ __dko_dotfiles__update() {
 }
 
 __dko_dotfiles__update_secret() {
-  __dko_status "Updating ~/.secret/"
   (
-    cd -- "${HOME}/.secret" ||
-      { __dko_err "No ~/.secret directory" && exit 1; }
+    cd -- "${HOME}/.secret" 2>/dev/null || {
+      __dko_warn 'Skipping ~/.secret/ update -- directory not found'
+      exit 0
+    }
+    __dko_status "Updating ~/.secret/"
     git pull --rebase --recurse-submodules || exit 1
     git log --no-merges --abbrev-commit --oneline ORIG_HEAD..
-  ) || __dko_err "Failed to update ~/.secret/"
+  )
 }
 
 __dko_dotfiles__update_daily() {
@@ -102,7 +104,7 @@ __dko_dotfiles__update_daily() {
 
   if [ -x /usr/bin/fzf ]; then
     __dko_ok "fzf installed by system package manager"
-  elif [[ -x "${DKO_BREW_PREFIX}/opt/fzf/install" ]] ||
+  elif [[ -x "${HOMEBREW_PREFIX}/opt/fzf/install" ]] ||
     [[ -d "${XDG_CONFIG_HOME}/fzf" ]] ||
     [[ -d "${HOME}/.fzf" ]]; then
     __dko_dotfiles__update_fzf
@@ -110,16 +112,15 @@ __dko_dotfiles__update_daily() {
     __dko_warn "fzf is not installed"
   fi
 
-  [ -d "$FNM_DIR" ] && __dko_dotfiles__node__update_fnm
+  __dko_dotfiles__node__update_fnm
 
   __dko_dotfiles__go__require_go && __dko_dotfiles__go__update_go_packages
 
-  __dko_dotfiles__ruby__require_chruby &&
-    __dko_dotfiles__ruby__require_rubygems && __dko_dotfiles__ruby__update_gems
+  __dko_dotfiles__ruby__require_rubygems && __dko_dotfiles__ruby__update_gems
 
-  __dko_dotfiles__php__require_composer && {
+  __dko_has composer && {
     __dko_dotfiles__php__update_composer
-    __dko_dotfiles__php__require_phpcs && __dko_dotfiles__php__update_wpcs
+    __dko_has phpcs && __dko_dotfiles__php__update_wpcs
   }
 
   __dko_has pyenv && {
@@ -133,14 +134,6 @@ __dko_dotfiles__update_daily() {
 # ------------------------------------------------------------------------------
 # Private utilities
 # ------------------------------------------------------------------------------
-
-__dko_dotfiles__pyenv_system() {
-  # switch to brew's python (fallback to system if no brew python)
-  __dko_has pyenv &&
-    __dko_status "Switching to system python to upgrade brew packages" &&
-    pyenv shell system || exit 1 &&
-    python --version
-}
 
 # probably don't need this as long as running updates in subshells
 __dko_dotfiles__pyenv_global() {
@@ -158,9 +151,9 @@ __dko_dotfiles__update_fzf() {
 
   if [ -x /usr/bin/fzf ]; then
     __dko_ok "fzf installed by system package manager"
-  elif [[ -x "${DKO_BREW_PREFIX}/opt/fzf/install" ]]; then
+  elif [[ -x "${HOMEBREW_PREFIX}/opt/fzf/install" ]]; then
     __dko_status "fzf was installed via brew, re-running installer"
-    installer="${DKO_BREW_PREFIX}/opt/fzf/install"
+    installer="${HOMEBREW_PREFIX}/opt/fzf/install"
   elif [[ -d "${HOME}/.fzf" ]]; then
     __dko_status "fzf was installed in ~/.fzf"
     installer="${HOME}/.fzf/install"
@@ -188,13 +181,6 @@ __dko_dotfiles__update_fzf() {
 # ----------------------------------------------------------------------------
 
 # pass any arg to silence
-__dko_dotfiles__ruby__require_chruby() {
-  [[ -n "$RUBY_VERSION" ]] && return 0
-  __dko_warn "System ruby detected! Please install and use chruby"
-  return 1
-}
-
-# pass any arg to silence
 __dko_dotfiles__ruby__require_rubygems() {
   __dko_has gem && return 0
   __dko_warn "rubygems is not installed"
@@ -207,7 +193,6 @@ __dko_dotfiles__ruby__require_rubygems() {
 
 __dko_dotfiles__ruby__update_gems() {
   __dko_status "Updating gems"
-  __dko_dotfiles__ruby__require_chruby || return 1
   __dko_dotfiles__ruby__require_rubygems || return 1
 
   __dko_status "Updating RubyGems itself for ruby: ${RUBY_VERSION}"
@@ -271,7 +256,7 @@ __dko_dotfiles__node__update_fnm() {
       "${DOTFILES}/bootstrap/fnm"
       ;;
     *arwin*)
-      __dko_dotfiles__darwin__require_brew || return 1
+      __dko_has brew || return 1
 
       if __dko_has brew; then
         if __dko_has fnm; then
@@ -362,18 +347,11 @@ __dko_dotfiles__py__update_neovim_python() {
 # PHP
 # ----------------------------------------------------------------------------
 
-# pass any arg to silence
-__dko_dotfiles__php__require_composer() {
-  __dko_has composer && return 0
-  (( $# == 0 )) && __dko_warn "composer is not installed"
-  return 1
-}
-
 __dko_dotfiles__php__update_composer() {
   __dko_status "Updating composer"
-  __dko_dotfiles__php__require_composer || return 1
+  __dko_has composer || return 1
 
-  if [[ -x "${DKO_BREW_PREFIX}/bin/composer" ]]; then
+  if [[ -x "${HOMEBREW_PREFIX}/bin/composer" ]]; then
     __dko_ok "composer was installed via brew (yay)"
   else
     __dko_status_ "Updating composer itself"
@@ -383,23 +361,13 @@ __dko_dotfiles__php__update_composer() {
     }
   fi
 
-  if [[ -f "$COMPOSER_HOME/composer.json" ]]; then
+  if [[ -f "${COMPOSER_HOME}/composer.json" ]]; then
     __dko_status "Updating composer global packages"
     composer global update || {
       __dko_err "Could not update global packages"
       return 1
     }
   fi
-}
-
-# pass any arg to silence
-__dko_dotfiles__php__require_phpcs() {
-  __dko_has phpcs && return 0
-  (( $# == 0 )) && {
-    __dko_warn "phpcs is not installed. Install via composer global require"
-    __dko_warn_ "and run again, or set installed_paths manually"
-  }
-  return 1
 }
 
 __dko_dotfiles__php__update_wpcs() {
@@ -412,8 +380,8 @@ __dko_dotfiles__php__update_wpcs() {
   # --------------------------------------------------------------------------
 
   __dko_status "Updating wpcs"
-  __dko_dotfiles__php__require_composer || return 1
-  __dko_dotfiles__php__require_phpcs || return 1
+  __dko_has composer || return 1
+  __dko_has phpcs || return 1
 
   if [[ ! -d "$wpcs_path" ]]; then
     mkdir -p "${sources_path}"
@@ -526,38 +494,33 @@ __dko_dotfiles__linux__deb__update() {
 # ------------------------------------------------------------------------------
 
 __dko_dotfiles__darwin__update_mac() {
-  # ST: Avoid automatic macOS system updates since we might be on unsupported hardware
-  # __dko_status "macOS system update"
-  # sudo softwareupdate --install --all
-  # 
-  # __dko_status "xcode and cli update"
-  # sudo xcode-select --install
+  __dko_status "macOS system update"
+  softwareupdate --install --all --force
 
-  __dko_has "mas" && mas upgrade
+  __dko_status "xcode and cli update"
+  sudo xcode-select --install
+
+  __dko_has mas && mas upgrade
 }
 
 # pass any arg to silence
 __dko_dotfiles__darwin__require_latest_xcode() {
   local v
+  # 14.0.0
   v="$(xcodebuild -version | awk 'NR==1{print $2}')"
-  if [[ "$v" == "${latest_xcode_major}."* ]]; then
-    __dko_ok "Found Xcode ${v}"
+  # 14 (trim until .)
+  v="${v%%.*}"
+  if (( v <= latest_xcode_major )); then
+    __dko_ok "Found Xcode >= v${v}"
     return 0
   fi
   __dko_err "Found Xcode ${v}, please install ${latest_xcode_major}.x.x"
   return 1
 }
 
-# pass any arg to silence
-__dko_dotfiles__darwin__require_brew() {
-  __dko_has brew && return 0
-  (( $# == 0 )) && __dko_warn "Homebrew is not installed"
-  return 1
-}
-
 __dko_dotfiles__darwin__update_brew() {
-  # __dko_dotfiles__darwin__require_latest_xcode || return 1
-  __dko_dotfiles__darwin__require_brew || return 1
+  __dko_dotfiles__darwin__require_latest_xcode || return 1
+  __dko_has brew || return 1
 
   __dko_status "Updating homebrew"
   (
@@ -565,16 +528,13 @@ __dko_dotfiles__darwin__update_brew() {
     # enter dotfiles dir to do this in case user has any gem flags or local
     # vendor bundle that will cause use of local gems
     __dko_dotfiles__cd || exit 1
-    __dko_dotfiles__pyenv_system
 
     __dko_status "brew update"
     brew update || exit 1
 
     # check if needed
     local outdated
-    # Get outdated items and strip out any that we don't want upgraded
-    outdated="$( brew outdated --quiet | sed s/'vagrant'// | sed s/'virtualbox-extension-pack'// | sed s/'virtualbox'// | tr '\n' ' ' )"
-
+    # outdated="$(brew outdated --quiet)"
     [[ -z "$outdated" ]] && {
       __dko_ok "Packages up-to-date"
       exit
@@ -582,11 +542,10 @@ __dko_dotfiles__darwin__update_brew() {
 
     # Upgrade remaining
     __dko_status "brew upgrade"
-    for word in $outdated; do
-      # We'll manually cleanup later
-      HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade "$word";
-    done
+    # We'll manually cleanup later
+    # HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade || exit 1
     __dko_ok "Upgrade complete"
+
     __dko_dotfiles__darwin__update_brew_postupgrade "$outdated"
   ) && {
     __dko_status "brew cleanup - clean up old versions and prune dead symlinks"
