Change how we check if Composer exists

diff --git a/php/install-composer-packages b/php/install-composer-packages
--- a/php/install-composer-packages
+++ b/php/install-composer-packages
@@ -16,10 +16,16 @@ fi
 # Main
 # =============================================================================
 
-[ ! -x 'composer' ] && {
+# [ ! -x 'composer' ] && {
+#   __dko_err "composer is not installed"
+#   exit 1
+# }
+
+if ! [ -x "$(command -v composer)" ]; then
+  # echo 'Error: git is not installed.' >&2
   __dko_err "composer is not installed"
   exit 1
-}
+fi
 
 __install() {
   composer diagnose
